routes/web.php
<?php

use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

Route::get('/', [UserController::class, 'create']);
Route::resource('users', UserController::class)->only(['show', 'store']);

app/Models/Article.php
<?php

declare(strict_types=1);

namespace App\Models;

use Illuminate\Database\Eloquent\{
    Model,
    Relations\BelongsTo,
    SoftDeletes
};

class Article extends Model
{
    use SoftDeletes;

    protected $fillable = [
        'text',
        'deleted_at'
    ];

    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    public function isAuthor(User $user): bool|null
    {
        if ($this->trashed()) {
            return null;
        }

        return $this->user->id === $user->id;
    }
}

app/Models/User.php
<?php

declare(strict_types=1);

namespace App\Models;

use Illuminate\{
    Database\Eloquent\Relations\HasMany,
    Notifications\Notifiable,
    Database\Eloquent\Factories\HasFactory,
    Foundation\Auth\User as Authenticatable
};

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    public const MALE = 0;
    public const FEMALE = 1;

    public static array $genders = [
        self::MALE  => 'male',
        self::FEMALE => 'female',
    ];

    protected $fillable = [
        'name',
        'surname',
        'nickname',
        'avatar',
        'gender',
        'email_notify',
        'phone',
        'email',
    ];

    protected $casts = [
        'email_verified_at' => 'datetime',
        'email_notify'      => 'boolean',
    ];

    public function articles(): HasMany
    {
        return $this->hasMany(Article::class);
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/UserController.php
<?php

declare(strict_types=1);

namespace App\Http\Controllers;

use App\{Http\Requests\StoreUserRequest, Models\Article, Services\UserService, Models\User};
use Illuminate\View\View;

class UserController extends Controller
{
    /**
     * @var UserService
     */
    private UserService $userService;

    private string $templatePath = 'users.';

    public function __construct(UserService $userService)
    {
        $this->userService = $userService;
    }

    public function create(): View
    {
        return view($this->templatePath . __FUNCTION__);
    }

    public function store(StoreUserRequest $request)
    {
        $user = $this->userService->storeElement($request);

        return redirect()->route('users.show', $user);
    }

    public function show(User $user): View
    {
        return view($this->templatePath . __FUNCTION__, compact('user'));
    }
}

resources/views/users/create.blade.php
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>PHP Test</title>
    <link rel="stylesheet" href="{{ asset('css/main.css') }}">
</head>
<body>
@if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
<div class="wrapper">
    <main class="main-content">
        <div class='edit-profile'>
            <h2 class="heading">Создать профиль</h2>
            <form class='form' id='form' method='POST' enctype='multipart/form-data' action="{{ route('users.store') }}">
                @csrf
                <ul class="form__list">
                    <li class="form__item">
                        <label class='form__label' for="nickname">Никнейм:</label>
                        <input class='form__input' id='nickname' name="nickname" type="text">
                    </li>
                    <li class="form__item">
                        <label class='form__label' for="name">Имя:</label>
                        <input class='form__input' id='name' name="name" type="text">
                    </li>
                    <li class="form__item">
                        <label class='form__label' for="surname">Фамилия:</label>
                        <input class='form__input' id='surname' name="surname" type="text">
                    </li>
                    <li class="form__item">
                        <label class='form__label' for="email">Email:</label>
                        <input class='form__input' id='email' name="email" type="email">
                    </li>
                    <li class="form__item">
                        <label class='form__inline-label' for="avatar">Аватар:</label>
                        <input class='form__inline-input' id='avatar' name="avatar" type="file">
                    </li>
                    <li class="form__item">
                        <label class='form__label' for="phone">Телефон:</label>
                        <input class='form__input' id='phone' name="phone" type="text">
                    </li>
                    <li class="form__item">
                        <div class="form__title">Пол:</div>
                        <label class='form__inline-label' for="male">Мужской</label>
                        <input class='form__inline-input' name='gender' id='male' type="radio" value="0">
                        <label class='form__inline-label' for="female">Женский</label>
                        <input class='form__inline-input' name='gender' id='female' type="radio" value="1">
                    </li>
                    <li class="form__item">
                        <label class='form__inline-label' for="showPhone">Я согласен получать email-рассылку</label>
                        <input class='form__inline-input' id='showPhone' type="checkbox" name="email_notify" value="1">
                    </li>
                    <li class="form__item">
                        <button class='form__button' type="submit">Отправить</button>
                    </li>
                </ul>
            </form>
        </div>
    </main>
</div>
</body>
</html>

resources/views/users/show.blade.php
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>PHP Test</title>
    <link rel="stylesheet" href="{{ asset('css/main.css') }}">
</head>
<body>
<div class="wrapper">
    <main class="main-content">
        <div class="my-profile">
            <h2 class="heading">Мой профиль</h2>
            <div class="profile">
                <div class="avatar">
                    @if($user->avatar)
                        <img src="{{ \App\Components\FileManager::getPathByFile($user->avatar) }}" alt="Аватар" class="avatar__pic">
                    @else
                        <img src="{{ asset('images/image.jpg') }}" alt="Аватар" class="avatar__pic">
                    @endif
                </div>
                <div class="information">
                    <div class="nickname">{{ $user->nickname }}</div>
                    <div class="user-name">
                        <span class="name">{{ $user->name }}</span>
                        <span class="surname">{{ $user->surname }}</span>
                    </div>
                    <a href='tel:{{$user->phone}}' class="phone">{{ $user->phone }}</a>
                </div>
            </div>
        </div>
        <div class='edit-profile'>
            <h2 class="heading">Профиль</h2>
            <form class='form' id='form' method='POST' enctype='multipart/form-data'>
                <ul class="form__list">
                    <li class="form__item">
                        <label class='form__label' for="nickname">Никнейм:</label>
                        <input class='form__input' id='nickname' type="text" value="{{ $user->nickname }}" readonly>
                    </li>
                    <li class="form__item">
                        <label class='form__label' for="name">Имя:</label>
                        <input class='form__input' id='name' type="text" value="{{ $user->name }}" readonly>
                    </li>
                    <li class="form__item">
                        <label class='form__label' for="surname">Фамилия:</label>
                        <input class='form__input' id='surname' type="text" value="{{ $user->surname }}" readonly>
                    </li>
                    <li class="form__item">
                        <label class='form__label' for="phone">Телефон:</label>
                        <input class='form__input' id='phone' type="text" value="{{ $user->phone }}" readonly>
                    </li>
                    <li class="form__item">
                        <label class='form__label' for="email">Почта:</label>
                        <input class='form__input' id='email' type="email" value="{{ $user->email }}" readonly>
                    </li>
                    <li class="form__item">
                        <label class="form__title">Пол:</label>
                        <input class='form__input' id='gender' type="text" value="{{ \App\Models\User::$genders[$user->gender] }}" readonly>
                    </li>
                    <li class="form__item">
                        @if($user->email_notify)
                            <label class='form__inline-label' for="showPhone">Я согласен получать email-рассылку</label>
                        @endif
                    </li>
                </ul>
            </form>
        </div>
    </main>
</div>
</body>
</html>